### ISSUE TITLE
client repository is not accessible

### ISSUE THREAD

**Issue by anapsix** [webhookrelay/homebrew-tap#1]
https://github.com/webhookrelay/homebrew-tap/blob/497c0d96d9b62cebd295f0a884ee3d6c0af4ecd9/relay.rb#L6

client repository is no longer accessible: either became private or deleted

**Comment by rusenask** [comment]
Hi, sorry about that, there were some changes in the distribution and updates of the client. I will push updated formula asap.

**Comment by rusenask** [comment]
Should be fixed now :)

**Comment by anapsix** [comment]
confirmed, many thanks!
